name = "johnyos"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "web_dist"
binding = "ASSETS"

[vars]
LINE_CHANNEL_ID = "2010502491"
SUPABASE_URL = "https://amcutibopnfasxrfexdi.supabase.co"
